# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_paths.ipynb.

# %% auto 0
__all__ = ['NBKS_DIR', 'ROOT_DIR', 'EXPL_DIR', 'DATA_DIR', 'RESULTS_DIR', 'FIGURES_DIR']

# %% ../nbs/00_paths.ipynb 3
import os

# %% ../nbs/00_paths.ipynb 4
'''----------------------------------------------------
NOTE: RELATIVE DEFINITIONS
----------------------------------------------------'''

# nbdev nbs directory, i.e. `nbs/``
NBKS_DIR = os.path.abspath('')

# project root directory
ROOT_DIR = os.path.join(NBKS_DIR, '..')

# where example notebooks are stored, i.e. `examples/`
EXPL_DIR = os.path.join(ROOT_DIR, 'examples')

# where small data is stored, i.e. `data/`
DATA_DIR = os.path.join(ROOT_DIR, 'data')

# where small data is stored, i.e. `results/`
RESULTS_DIR = os.path.join(ROOT_DIR, 'results')

# where small data is stored, i.e. `figures/`
FIGURES_DIR = os.path.join(ROOT_DIR, 'figures')
