# Generated by Django 4.2.6 on 2023-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subsystems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
