"""
This file was generated by 'versioneer.py' (0.18) from
revision-control system data, or from the parent directory name of an
unpacked source archive. Distribution tarballs contain a pre-generated copy
of this file.
"""

# pylint: disable=unused-variable, invalid-name

import json

version_json = """
{
 "date": "2021-10-13T17:35:01+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "06532f2f8b85668010eb061fb0a5137b823e5184",
 "version": "0.4.7"
}
"""  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
