WM_MOUSEMOVE = "WM_MOUSEMOVEessage",
WM_LBUTTONDOWN = "WM_LBUTTONDOWNessage",
WM_LBUTTONUP = "WM_LBUTTONUPessage",
WM_LBUTTONDBLCLK = "WM_LBUTTONDBLCLKessage",
WM_RBUTTONDOWN = "WM_RBUTTONDOWNessage",
WM_RBUTTONUP = "WM_RBUTTONUPessage",
WM_RBUTTONDBLCLK = "WM_RBUTTONDBLCLKessage",
WM_MBUTTONDOWN = "WM_MBUTTONDOWNessage",
WM_MBUTTONUP = "WM_MBUTTONUPessage",
WM_MBUTTONDBLCLK = "WM_MBUTTONDBLCLKessage"

ADD = "add"
APPLICATION = "application"
DELETE = "delete"
MODIFY = "modify"

MESSAGE = "%message"
X = "%x"
Y = "%y"
