
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-09T13:52:00-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "893ec2a33b543c570350c73e21fd2e860e2c079d",
 "version": "0.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
