# Autogenerated by devscripts/update-version.py

__version__ = '2023.11.13.005826'

RELEASE_GIT_HEAD = '87264d4fdadcddd91289b968dd0e4bf58d449267'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2023.11.13.005826dev'
