###default __init__ 
__version__='1.0.0' 
 
from pathlib import Path
import sys
path = str(Path(Path(__file__).parent.absolute()).parent.absolute())
sys.path.insert(0, path)


from biopax.utils.class_utils import tostring

##from biopax.templatereactionregulation import Templatereactionregulation
from biopax.templatereactionregulation import TemplateReactionRegulation
##from biopax.entityreference import Entityreference
from biopax.entityreference import EntityReference
##from biopax.evidencecodevocabulary import Evidencecodevocabulary
from biopax.evidencecodevocabulary import EvidenceCodeVocabulary
##from biopax.proteinreference import Proteinreference
from biopax.proteinreference import ProteinReference
##from biopax.covalentbindingfeature import Covalentbindingfeature
from biopax.covalentbindingfeature import CovalentBindingFeature
##from biopax.sequenceregionvocabulary import Sequenceregionvocabulary
from biopax.sequenceregionvocabulary import SequenceRegionVocabulary
##from biopax.relationshipxref import Relationshipxref
from biopax.relationshipxref import RelationshipXref
##from biopax.protein import Protein
from biopax.protein import Protein
##from biopax.transportwithbiochemicalreaction import Transportwithbiochemicalreaction
from biopax.transportwithbiochemicalreaction import TransportWithBiochemicalReaction
##from biopax.rna import Rna
from biopax.rna import Rna
##from biopax.rnareference import Rnareference
from biopax.rnareference import RnaReference
##from biopax.cellvocabulary import Cellvocabulary
from biopax.cellvocabulary import CellVocabulary
##from biopax.provenance import Provenance
from biopax.provenance import Provenance
##from biopax.evidence import Evidence
from biopax.evidence import Evidence
##from biopax.conversion import Conversion
from biopax.conversion import Conversion
##from biopax.physicalentity import Physicalentity
from biopax.physicalentity import PhysicalEntity
##from biopax.deltag import Deltag
from biopax.deltag import DeltaG
##from biopax.interaction import Interaction
from biopax.interaction import Interaction
##from biopax.dnareference import Dnareference
from biopax.dnareference import DnaReference
##from biopax.biosource import Biosource
from biopax.biosource import BioSource
##from biopax.entityreferencetypevocabulary import Entityreferencetypevocabulary
from biopax.entityreferencetypevocabulary import EntityReferenceTypeVocabulary
##from biopax.xref import Xref
from biopax.xref import Xref
##from biopax.fragmentfeature import Fragmentfeature
from biopax.fragmentfeature import FragmentFeature
##from biopax.relationshiptypevocabulary import Relationshiptypevocabulary
from biopax.relationshiptypevocabulary import RelationshipTypeVocabulary
##from biopax.chemicalstructure import Chemicalstructure
from biopax.chemicalstructure import ChemicalStructure
##from biopax.experimentalformvocabulary import Experimentalformvocabulary
from biopax.experimentalformvocabulary import ExperimentalFormVocabulary
##from biopax.interactionvocabulary import Interactionvocabulary
from biopax.interactionvocabulary import InteractionVocabulary
##from biopax.degradation import Degradation
from biopax.degradation import Degradation
##from biopax.sequencemodificationvocabulary import Sequencemodificationvocabulary
from biopax.sequencemodificationvocabulary import SequenceModificationVocabulary
##from biopax.templatereaction import Templatereaction
from biopax.templatereaction import TemplateReaction
##from biopax.bindingfeature import Bindingfeature
from biopax.bindingfeature import BindingFeature
##from biopax.pathway import Pathway
from biopax.pathway import Pathway
##from biopax.publicationxref import Publicationxref
from biopax.publicationxref import PublicationXref
##from biopax.modulation import Modulation
from biopax.modulation import Modulation
##from biopax.controlledvocabulary import Controlledvocabulary
from biopax.controlledvocabulary import ControlledVocabulary
##from biopax.sequenceinterval import Sequenceinterval
from biopax.sequenceinterval import SequenceInterval
##from biopax.dnaregion import Dnaregion
from biopax.dnaregion import DnaRegion
##from biopax.sequencelocation import Sequencelocation
from biopax.sequencelocation import SequenceLocation
##from biopax.kprime import Kprime
from biopax.kprime import KPrime
##from biopax.biochemicalpathwaystep import Biochemicalpathwaystep
from biopax.biochemicalpathwaystep import BiochemicalPathwayStep
##from biopax.entityfeature import Entityfeature
from biopax.entityfeature import EntityFeature
##from biopax.smallmoleculereference import Smallmoleculereference
from biopax.smallmoleculereference import SmallMoleculeReference
##from biopax.experimentalform import Experimentalform
from biopax.experimentalform import ExperimentalForm
##from biopax.pathwaystep import Pathwaystep
from biopax.pathwaystep import PathwayStep
##from biopax.rnaregion import Rnaregion
from biopax.rnaregion import RnaRegion
##from biopax.rnaregionreference import Rnaregionreference
from biopax.rnaregionreference import RnaRegionReference
##from biopax.molecularinteraction import Molecularinteraction
from biopax.molecularinteraction import MolecularInteraction
##from biopax.tissuevocabulary import Tissuevocabulary
from biopax.tissuevocabulary import TissueVocabulary
##from biopax.biochemicalreaction import Biochemicalreaction
from biopax.biochemicalreaction import BiochemicalReaction
##from biopax.complexassembly import Complexassembly
from biopax.complexassembly import ComplexAssembly
##from biopax.catalysis import Catalysis
from biopax.catalysis import Catalysis
##from biopax.control import Control
from biopax.control import Control
##from biopax.transport import Transport
from biopax.transport import Transport
##from biopax.modificationfeature import Modificationfeature
from biopax.modificationfeature import ModificationFeature
##from biopax.complex import Complex
from biopax.complex import Complex
##from biopax.cellularlocationvocabulary import Cellularlocationvocabulary
from biopax.cellularlocationvocabulary import CellularLocationVocabulary
##from biopax.phenotypevocabulary import Phenotypevocabulary
from biopax.phenotypevocabulary import PhenotypeVocabulary
##from biopax.score import Score
from biopax.score import Score
##from biopax.gene import Gene
from biopax.gene import Gene
##from biopax.stoichiometry import Stoichiometry
from biopax.stoichiometry import Stoichiometry
##from biopax.smallmolecule import Smallmolecule
from biopax.smallmolecule import SmallMolecule
##from biopax.dna import Dna
from biopax.dna import Dna
##from biopax.geneticinteraction import Geneticinteraction
from biopax.geneticinteraction import GeneticInteraction
##from biopax.unificationxref import Unificationxref
from biopax.unificationxref import UnificationXref
##from biopax.sequencesite import Sequencesite
from biopax.sequencesite import SequenceSite
##from biopax.dnaregionreference import Dnaregionreference
from biopax.dnaregionreference import DnaRegionReference
##from biopax.utilityclass import Utilityclass
from biopax.utilityclass import UtilityClass
##from biopax.entity import Entity
from biopax.entity import Entity
######## unexpected name: <N2aadcc1d61524d598330ae06e6d6d2c2> 
  


