# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collections_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import collections_pb2 as collections__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ollections_service.proto\x12\narc_vector\x1a\x11\x63ollections.proto2\xb4\x07\n\x0b\x43ollections\x12T\n\x03Get\x12$.arc_vector.GetCollectionInfoRequest\x1a%.arc_vector.GetCollectionInfoResponse\"\x00\x12Q\n\x04List\x12\".arc_vector.ListCollectionsRequest\x1a#.arc_vector.ListCollectionsResponse\"\x00\x12Q\n\x06\x43reate\x12\x1c.arc_vector.CreateCollection\x1a\'.arc_vector.CollectionOperationResponse\"\x00\x12Q\n\x06Update\x12\x1c.arc_vector.UpdateCollection\x1a\'.arc_vector.CollectionOperationResponse\"\x00\x12Q\n\x06\x44\x65lete\x12\x1c.arc_vector.DeleteCollection\x1a\'.arc_vector.CollectionOperationResponse\"\x00\x12U\n\rUpdateAliases\x12\x19.arc_vector.ChangeAliases\x1a\'.arc_vector.CollectionOperationResponse\"\x00\x12\x64\n\x15ListCollectionAliases\x12(.arc_vector.ListCollectionAliasesRequest\x1a\x1f.arc_vector.ListAliasesResponse\"\x00\x12P\n\x0bListAliases\x12\x1e.arc_vector.ListAliasesRequest\x1a\x1f.arc_vector.ListAliasesResponse\"\x00\x12n\n\x15\x43ollectionClusterInfo\x12(.arc_vector.CollectionClusterInfoRequest\x1a).arc_vector.CollectionClusterInfoResponse\"\x00\x12\x83\x01\n\x1cUpdateCollectionClusterSetup\x12/.arc_vector.UpdateCollectionClusterSetupRequest\x1a\x30.arc_vector.UpdateCollectionClusterSetupResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collections_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COLLECTIONS']._serialized_start=61
  _globals['_COLLECTIONS']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
