# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshots_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17snapshots_service.proto\x12\narc_vector\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n\x19\x43reateFullSnapshotRequest\"\x1a\n\x18ListFullSnapshotsRequest\"2\n\x19\x44\x65leteFullSnapshotRequest\x12\x15\n\rsnapshot_name\x18\x01 \x01(\t\"0\n\x15\x43reateSnapshotRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\"/\n\x14ListSnapshotsRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\"G\n\x15\x44\x65leteSnapshotRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\x15\n\rsnapshot_name\x18\x02 \x01(\t\"d\n\x13SnapshotDescription\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\rcreation_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04size\x18\x03 \x01(\x03\"e\n\x16\x43reateSnapshotResponse\x12=\n\x14snapshot_description\x18\x01 \x01(\x0b\x32\x1f.arc_vector.SnapshotDescription\x12\x0c\n\x04time\x18\x02 \x01(\x01\"e\n\x15ListSnapshotsResponse\x12>\n\x15snapshot_descriptions\x18\x01 \x03(\x0b\x32\x1f.arc_vector.SnapshotDescription\x12\x0c\n\x04time\x18\x02 \x01(\x01\"&\n\x16\x44\x65leteSnapshotResponse\x12\x0c\n\x04time\x18\x01 \x01(\x01\x32\x8d\x04\n\tSnapshots\x12Q\n\x06\x43reate\x12!.arc_vector.CreateSnapshotRequest\x1a\".arc_vector.CreateSnapshotResponse\"\x00\x12M\n\x04List\x12 .arc_vector.ListSnapshotsRequest\x1a!.arc_vector.ListSnapshotsResponse\"\x00\x12Q\n\x06\x44\x65lete\x12!.arc_vector.DeleteSnapshotRequest\x1a\".arc_vector.DeleteSnapshotResponse\"\x00\x12Y\n\nCreateFull\x12%.arc_vector.CreateFullSnapshotRequest\x1a\".arc_vector.CreateSnapshotResponse\"\x00\x12U\n\x08ListFull\x12$.arc_vector.ListFullSnapshotsRequest\x1a!.arc_vector.ListSnapshotsResponse\"\x00\x12Y\n\nDeleteFull\x12%.arc_vector.DeleteFullSnapshotRequest\x1a\".arc_vector.DeleteSnapshotResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snapshots_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATEFULLSNAPSHOTREQUEST']._serialized_start=102
  _globals['_CREATEFULLSNAPSHOTREQUEST']._serialized_end=129
  _globals['_LISTFULLSNAPSHOTSREQUEST']._serialized_start=131
  _globals['_LISTFULLSNAPSHOTSREQUEST']._serialized_end=157
  _globals['_DELETEFULLSNAPSHOTREQUEST']._serialized_start=159
  _globals['_DELETEFULLSNAPSHOTREQUEST']._serialized_end=209
  _globals['_CREATESNAPSHOTREQUEST']._serialized_start=211
  _globals['_CREATESNAPSHOTREQUEST']._serialized_end=259
  _globals['_LISTSNAPSHOTSREQUEST']._serialized_start=261
  _globals['_LISTSNAPSHOTSREQUEST']._serialized_end=308
  _globals['_DELETESNAPSHOTREQUEST']._serialized_start=310
  _globals['_DELETESNAPSHOTREQUEST']._serialized_end=381
  _globals['_SNAPSHOTDESCRIPTION']._serialized_start=383
  _globals['_SNAPSHOTDESCRIPTION']._serialized_end=483
  _globals['_CREATESNAPSHOTRESPONSE']._serialized_start=485
  _globals['_CREATESNAPSHOTRESPONSE']._serialized_end=586
  _globals['_LISTSNAPSHOTSRESPONSE']._serialized_start=588
  _globals['_LISTSNAPSHOTSRESPONSE']._serialized_end=689
  _globals['_DELETESNAPSHOTRESPONSE']._serialized_start=691
  _globals['_DELETESNAPSHOTRESPONSE']._serialized_end=729
  _globals['_SNAPSHOTS']._serialized_start=732
  _globals['_SNAPSHOTS']._serialized_end=1257
# @@protoc_insertion_point(module_scope)
