# Generated by Django 4.2.6 on 2023-11-10 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subsystems', '0002_alter_subsystem_name_alter_system_name'),
        ('netbox_rolesandgroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techrole',
            name='role',
        ),
        migrations.AddField(
            model_name='techrole',
            name='roles',
            field=models.ManyToManyField(related_name='techroles', to='netbox_rolesandgroups.systemrole'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_role', to='netbox_subsystems.subsystem'),
        ),
    ]
