# Generated by Django 4.2.6 on 2023-11-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subsystems', '0002_alter_subsystem_name_alter_system_name'),
        ('netbox_rolesandgroups', '0002_remove_techrole_role_techrole_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrole',
            name='subsystems',
            field=models.ManyToManyField(related_name='roles', to='netbox_subsystems.subsystem'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='netbox_subsystems.subsystem'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='netbox_subsystems.system'),
        ),
    ]
