# Generated by Django 4.2.6 on 2023-11-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rolesandgroups', '0003_systemrole_subsystems_alter_systemrole_subsystem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrole',
            name='subsystem',
        ),
    ]
