
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-09T11:41:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b51dab6c8205145330fe3432f5dfd24ed9f8d60d",
 "version": "2023.11.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
