
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-08T11:03:31-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a84bd298d1f606fe9f34d30dabd3d7aa1a414496",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
