
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-09T12:12:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1554482406fac902ea050291173406fb640c8efe",
 "version": "2023.11.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
