# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ALogAnalyze/UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 951, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.ALogAnalyze = QtWidgets.QWidget()
        self.ALogAnalyze.setObjectName("ALogAnalyze")
        self.AAInfoTextEdit = QtWidgets.QTextEdit(self.ALogAnalyze)
        self.AAInfoTextEdit.setGeometry(QtCore.QRect(10, 270, 921, 271))
        self.AAInfoTextEdit.setAcceptRichText(False)
        self.AAInfoTextEdit.setObjectName("AAInfoTextEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.ALogAnalyze)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 921, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.AATemplateComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.AATemplateComboBox.setObjectName("AATemplateComboBox")
        self.gridLayout.addWidget(self.AATemplateComboBox, 0, 1, 1, 5)
        self.AAFilePathLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AAFilePathLineEdit.setObjectName("AAFilePathLineEdit")
        self.gridLayout.addWidget(self.AAFilePathLineEdit, 1, 1, 1, 4)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.AAFileSelectPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AAFileSelectPushButton.setObjectName("AAFileSelectPushButton")
        self.gridLayout.addWidget(self.AAFileSelectPushButton, 1, 5, 1, 1)
        self.AADataIndexLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AADataIndexLineEdit.setObjectName("AADataIndexLineEdit")
        self.gridLayout.addWidget(self.AADataIndexLineEdit, 4, 1, 1, 5)
        self.AARegexTextEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.AARegexTextEdit.setAcceptRichText(False)
        self.AARegexTextEdit.setObjectName("AARegexTextEdit")
        self.gridLayout.addWidget(self.AARegexTextEdit, 2, 1, 1, 5)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.AAParseDataPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AAParseDataPushButton.setObjectName("AAParseDataPushButton")
        self.gridLayout.addWidget(self.AAParseDataPushButton, 5, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.AAXAxisLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.AAXAxisLineEdit.setObjectName("AAXAxisLineEdit")
        self.gridLayout.addWidget(self.AAXAxisLineEdit, 3, 1, 1, 5)
        self.AAPlotCurvePushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AAPlotCurvePushButton.setObjectName("AAPlotCurvePushButton")
        self.gridLayout.addWidget(self.AAPlotCurvePushButton, 5, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.ALogAnalyze, "")
        self.RegexGenerator = QtWidgets.QWidget()
        self.RegexGenerator.setObjectName("RegexGenerator")
        self.RGInputDataTextEdit = QtWidgets.QTextEdit(self.RegexGenerator)
        self.RGInputDataTextEdit.setGeometry(QtCore.QRect(40, 80, 861, 61))
        self.RGInputDataTextEdit.setAcceptRichText(False)
        self.RGInputDataTextEdit.setObjectName("RGInputDataTextEdit")
        self.label_9 = QtWidgets.QLabel(self.RegexGenerator)
        self.label_9.setGeometry(QtCore.QRect(40, 50, 81, 18))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.RegexGenerator)
        self.label_10.setGeometry(QtCore.QRect(40, 150, 81, 18))
        self.label_10.setObjectName("label_10")
        self.RGRegexTextEdit = QtWidgets.QTextEdit(self.RegexGenerator)
        self.RGRegexTextEdit.setGeometry(QtCore.QRect(40, 180, 861, 61))
        self.RGRegexTextEdit.setAcceptRichText(False)
        self.RGRegexTextEdit.setObjectName("RGRegexTextEdit")
        self.RGInfoTextEdit = QtWidgets.QTextEdit(self.RegexGenerator)
        self.RGInfoTextEdit.setGeometry(QtCore.QRect(40, 330, 861, 191))
        self.RGInfoTextEdit.setAcceptRichText(False)
        self.RGInfoTextEdit.setObjectName("RGInfoTextEdit")
        self.RGParseDataPushButton = QtWidgets.QPushButton(self.RegexGenerator)
        self.RGParseDataPushButton.setGeometry(QtCore.QRect(340, 290, 221, 26))
        self.RGParseDataPushButton.setObjectName("RGParseDataPushButton")
        self.label_11 = QtWidgets.QLabel(self.RegexGenerator)
        self.label_11.setGeometry(QtCore.QRect(40, 20, 71, 26))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.RGTemplateComboBox = QtWidgets.QComboBox(self.RegexGenerator)
        self.RGTemplateComboBox.setGeometry(QtCore.QRect(120, 20, 781, 26))
        self.RGTemplateComboBox.setObjectName("RGTemplateComboBox")
        self.label_14 = QtWidgets.QLabel(self.RegexGenerator)
        self.label_14.setGeometry(QtCore.QRect(40, 250, 71, 26))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.RGDataIndexLineEdit = QtWidgets.QLineEdit(self.RegexGenerator)
        self.RGDataIndexLineEdit.setGeometry(QtCore.QRect(122, 250, 781, 26))
        self.RGDataIndexLineEdit.setObjectName("RGDataIndexLineEdit")
        self.tabWidget.addTab(self.RegexGenerator, "")
        self.Plugins = QtWidgets.QWidget()
        self.Plugins.setObjectName("Plugins")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Plugins)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 931, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.PSVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.PSVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.PSVerticalLayout.setObjectName("PSVerticalLayout")
        self.PSPluginsComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.PSPluginsComboBox.setObjectName("PSPluginsComboBox")
        self.PSVerticalLayout.addWidget(self.PSPluginsComboBox)
        self.PSGridLayout = QtWidgets.QGridLayout()
        self.PSGridLayout.setObjectName("PSGridLayout")
        self.PSVerticalLayout.addLayout(self.PSGridLayout)
        self.PSRunPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PSRunPushButton.setObjectName("PSRunPushButton")
        self.PSVerticalLayout.addWidget(self.PSRunPushButton)
        self.PSInfoPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.PSInfoPlainTextEdit.setObjectName("PSInfoPlainTextEdit")
        self.PSVerticalLayout.addWidget(self.PSInfoPlainTextEdit)
        self.tabWidget.addTab(self.Plugins, "")
        self.Data3D = QtWidgets.QWidget()
        self.Data3D.setObjectName("Data3D")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Data3D)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 931, 531))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.D3DVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.D3DVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.D3DVerticalLayout.setObjectName("D3DVerticalLayout")
        self.D3DTypesComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.D3DTypesComboBox.setObjectName("D3DTypesComboBox")
        self.D3DVerticalLayout.addWidget(self.D3DTypesComboBox)
        self.D3DGridLayout = QtWidgets.QGridLayout()
        self.D3DGridLayout.setObjectName("D3DGridLayout")
        self.D3DVerticalLayout.addLayout(self.D3DGridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.D3DParsePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.D3DParsePushButton.setObjectName("D3DParsePushButton")
        self.horizontalLayout.addWidget(self.D3DParsePushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.D3DRunPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.D3DRunPushButton.setObjectName("D3DRunPushButton")
        self.horizontalLayout.addWidget(self.D3DRunPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.D3DVerticalLayout.addLayout(self.horizontalLayout)
        self.D3DInfoPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.D3DInfoPlainTextEdit.setObjectName("D3DInfoPlainTextEdit")
        self.D3DVerticalLayout.addWidget(self.D3DInfoPlainTextEdit)
        self.tabWidget.addTab(self.Data3D, "")
        self.DiffFrame = QtWidgets.QWidget()
        self.DiffFrame.setObjectName("DiffFrame")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.DiffFrame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 931, 531))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.DFVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.DFVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.DFVerticalLayout.setObjectName("DFVerticalLayout")
        self.DFTypesComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.DFTypesComboBox.setObjectName("DFTypesComboBox")
        self.DFVerticalLayout.addWidget(self.DFTypesComboBox)
        self.DFGridLayout = QtWidgets.QGridLayout()
        self.DFGridLayout.setObjectName("DFGridLayout")
        self.DFVerticalLayout.addLayout(self.DFGridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.DFParsePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.DFParsePushButton.setObjectName("DFParsePushButton")
        self.horizontalLayout_2.addWidget(self.DFParsePushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.DFRunPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.DFRunPushButton.setObjectName("DFRunPushButton")
        self.horizontalLayout_2.addWidget(self.DFRunPushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.DFVerticalLayout.addLayout(self.horizontalLayout_2)
        self.DFInfoPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        self.DFInfoPlainTextEdit.setObjectName("DFInfoPlainTextEdit")
        self.DFVerticalLayout.addWidget(self.DFInfoPlainTextEdit)
        self.tabWidget.addTab(self.DiffFrame, "")
        self.DataLive = QtWidgets.QWidget()
        self.DataLive.setObjectName("DataLive")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.DataLive)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 931, 531))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.DLVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.DLVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.DLVerticalLayout.setObjectName("DLVerticalLayout")
        self.DLTypesComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.DLTypesComboBox.setObjectName("DLTypesComboBox")
        self.DLVerticalLayout.addWidget(self.DLTypesComboBox)
        self.DLGridLayout = QtWidgets.QGridLayout()
        self.DLGridLayout.setObjectName("DLGridLayout")
        self.DLVerticalLayout.addLayout(self.DLGridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.DLParsePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.DLParsePushButton.setObjectName("DLParsePushButton")
        self.horizontalLayout_3.addWidget(self.DLParsePushButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.DLRunPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.DLRunPushButton.setObjectName("DLRunPushButton")
        self.horizontalLayout_3.addWidget(self.DLRunPushButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.DLVerticalLayout.addLayout(self.horizontalLayout_3)
        self.DLInfoPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_4)
        self.DLInfoPlainTextEdit.setObjectName("DLInfoPlainTextEdit")
        self.DLVerticalLayout.addWidget(self.DLInfoPlainTextEdit)
        self.tabWidget.addTab(self.DataLive, "")
        self.ArrayPlot = QtWidgets.QWidget()
        self.ArrayPlot.setObjectName("ArrayPlot")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.ArrayPlot)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 931, 541))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.APDataPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_5)
        self.APDataPlainTextEdit.setObjectName("APDataPlainTextEdit")
        self.verticalLayout.addWidget(self.APDataPlainTextEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.APRunPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.APRunPushButton.setObjectName("APRunPushButton")
        self.horizontalLayout_4.addWidget(self.APRunPushButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.ArrayPlot, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Android Log Analyze"))
        self.label_3.setText(_translate("MainWindow", "Regex:"))
        self.label.setText(_translate("MainWindow", "Template:"))
        self.AAFileSelectPushButton.setText(_translate("MainWindow", "File Select..."))
        self.label_7.setText(_translate("MainWindow", "Data Index:"))
        self.AAParseDataPushButton.setText(_translate("MainWindow", "Parse Data"))
        self.label_4.setText(_translate("MainWindow", "X Axis:"))
        self.AAPlotCurvePushButton.setText(_translate("MainWindow", "Plot Curve"))
        self.label_2.setText(_translate("MainWindow", "File Path:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ALogAnalyze), _translate("MainWindow", "ALogAnalyze"))
        self.label_9.setText(_translate("MainWindow", "Input Data:"))
        self.label_10.setText(_translate("MainWindow", "Regex:"))
        self.RGParseDataPushButton.setText(_translate("MainWindow", "Parse Data"))
        self.label_11.setText(_translate("MainWindow", "Template:"))
        self.label_14.setText(_translate("MainWindow", "Data Index:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RegexGenerator), _translate("MainWindow", "RegexGenerator"))
        self.PSRunPushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Plugins), _translate("MainWindow", "Plugins"))
        self.D3DParsePushButton.setText(_translate("MainWindow", "Parse"))
        self.D3DRunPushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data3D), _translate("MainWindow", "Data3D"))
        self.DFParsePushButton.setText(_translate("MainWindow", "Parse"))
        self.DFRunPushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DiffFrame), _translate("MainWindow", "DiffFrame"))
        self.DLParsePushButton.setText(_translate("MainWindow", "Parse"))
        self.DLRunPushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataLive), _translate("MainWindow", "DataLive"))
        self.APRunPushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ArrayPlot), _translate("MainWindow", "ArrayPlot"))
