# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.177.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccessList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'updated_at': 'str',
        'list': 'str',
        'owner': 'str',
        'type': 'str',
        'name': 'str',
        'is_active': 'bool'
    }

    attribute_map = {
        'updated_at': 'updated_at',
        'list': 'list',
        'owner': 'owner',
        'type': 'type',
        'name': 'name',
        'is_active': 'is_active'
    }

    def __init__(self, updated_at=None, list=None, owner=None, type=None, name=None, is_active=None):  # noqa: E501
        """AccessList - a model defined in Swagger"""  # noqa: E501
        self._updated_at = None
        self._list = None
        self._owner = None
        self._type = None
        self._name = None
        self._is_active = None
        self.discriminator = None
        if updated_at is not None:
            self.updated_at = updated_at
        if list is not None:
            self.list = list
        if owner is not None:
            self.owner = owner
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if is_active is not None:
            self.is_active = is_active

    @property
    def updated_at(self):
        """Gets the updated_at of this AccessList.  # noqa: E501


        :return: The updated_at of this AccessList.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AccessList.


        :param updated_at: The updated_at of this AccessList.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    @property
    def list(self):
        """Gets the list of this AccessList.  # noqa: E501


        :return: The list of this AccessList.  # noqa: E501
        :rtype: str
        """
        return self._list

    @list.setter
    def list(self, list):
        """Sets the list of this AccessList.


        :param list: The list of this AccessList.  # noqa: E501
        :type: str
        """

        self._list = list

    @property
    def owner(self):
        """Gets the owner of this AccessList.  # noqa: E501


        :return: The owner of this AccessList.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this AccessList.


        :param owner: The owner of this AccessList.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def type(self):
        """Gets the type of this AccessList.  # noqa: E501


        :return: The type of this AccessList.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AccessList.


        :param type: The type of this AccessList.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this AccessList.  # noqa: E501


        :return: The name of this AccessList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AccessList.


        :param name: The name of this AccessList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_active(self):
        """Gets the is_active of this AccessList.  # noqa: E501


        :return: The is_active of this AccessList.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this AccessList.


        :param is_active: The is_active of this AccessList.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccessList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
