# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.177.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryAdvice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message_id': 'str',
        'from_address_id': 'str',
        'to_address_id': 'str',
        'message_type': 'str',
        'delivered_at': 'str',
        'sender_reference': 'str',
        'system_id': 'float'
    }

    attribute_map = {
        'message_id': 'message_id',
        'from_address_id': 'from_address_id',
        'to_address_id': 'to_address_id',
        'message_type': 'message_type',
        'delivered_at': 'delivered_at',
        'sender_reference': 'sender_reference',
        'system_id': 'system_id'
    }

    def __init__(self, message_id=None, from_address_id=None, to_address_id=None, message_type=None, delivered_at=None, sender_reference=None, system_id=None):  # noqa: E501
        """DeliveryAdvice - a model defined in Swagger"""  # noqa: E501
        self._message_id = None
        self._from_address_id = None
        self._to_address_id = None
        self._message_type = None
        self._delivered_at = None
        self._sender_reference = None
        self._system_id = None
        self.discriminator = None
        if message_id is not None:
            self.message_id = message_id
        if from_address_id is not None:
            self.from_address_id = from_address_id
        if to_address_id is not None:
            self.to_address_id = to_address_id
        if message_type is not None:
            self.message_type = message_type
        if delivered_at is not None:
            self.delivered_at = delivered_at
        if sender_reference is not None:
            self.sender_reference = sender_reference
        if system_id is not None:
            self.system_id = system_id

    @property
    def message_id(self):
        """Gets the message_id of this DeliveryAdvice.  # noqa: E501


        :return: The message_id of this DeliveryAdvice.  # noqa: E501
        :rtype: str
        """
        return self._message_id

    @message_id.setter
    def message_id(self, message_id):
        """Sets the message_id of this DeliveryAdvice.


        :param message_id: The message_id of this DeliveryAdvice.  # noqa: E501
        :type: str
        """

        self._message_id = message_id

    @property
    def from_address_id(self):
        """Gets the from_address_id of this DeliveryAdvice.  # noqa: E501


        :return: The from_address_id of this DeliveryAdvice.  # noqa: E501
        :rtype: str
        """
        return self._from_address_id

    @from_address_id.setter
    def from_address_id(self, from_address_id):
        """Sets the from_address_id of this DeliveryAdvice.


        :param from_address_id: The from_address_id of this DeliveryAdvice.  # noqa: E501
        :type: str
        """

        self._from_address_id = from_address_id

    @property
    def to_address_id(self):
        """Gets the to_address_id of this DeliveryAdvice.  # noqa: E501


        :return: The to_address_id of this DeliveryAdvice.  # noqa: E501
        :rtype: str
        """
        return self._to_address_id

    @to_address_id.setter
    def to_address_id(self, to_address_id):
        """Sets the to_address_id of this DeliveryAdvice.


        :param to_address_id: The to_address_id of this DeliveryAdvice.  # noqa: E501
        :type: str
        """

        self._to_address_id = to_address_id

    @property
    def message_type(self):
        """Gets the message_type of this DeliveryAdvice.  # noqa: E501


        :return: The message_type of this DeliveryAdvice.  # noqa: E501
        :rtype: str
        """
        return self._message_type

    @message_type.setter
    def message_type(self, message_type):
        """Sets the message_type of this DeliveryAdvice.


        :param message_type: The message_type of this DeliveryAdvice.  # noqa: E501
        :type: str
        """

        self._message_type = message_type

    @property
    def delivered_at(self):
        """Gets the delivered_at of this DeliveryAdvice.  # noqa: E501


        :return: The delivered_at of this DeliveryAdvice.  # noqa: E501
        :rtype: str
        """
        return self._delivered_at

    @delivered_at.setter
    def delivered_at(self, delivered_at):
        """Sets the delivered_at of this DeliveryAdvice.


        :param delivered_at: The delivered_at of this DeliveryAdvice.  # noqa: E501
        :type: str
        """

        self._delivered_at = delivered_at

    @property
    def sender_reference(self):
        """Gets the sender_reference of this DeliveryAdvice.  # noqa: E501


        :return: The sender_reference of this DeliveryAdvice.  # noqa: E501
        :rtype: str
        """
        return self._sender_reference

    @sender_reference.setter
    def sender_reference(self, sender_reference):
        """Sets the sender_reference of this DeliveryAdvice.


        :param sender_reference: The sender_reference of this DeliveryAdvice.  # noqa: E501
        :type: str
        """

        self._sender_reference = sender_reference

    @property
    def system_id(self):
        """Gets the system_id of this DeliveryAdvice.  # noqa: E501


        :return: The system_id of this DeliveryAdvice.  # noqa: E501
        :rtype: float
        """
        return self._system_id

    @system_id.setter
    def system_id(self, system_id):
        """Sets the system_id of this DeliveryAdvice.


        :param system_id: The system_id of this DeliveryAdvice.  # noqa: E501
        :type: float
        """

        self._system_id = system_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryAdvice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryAdvice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
