# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.177.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessagesCount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to_id': 'str',
        'messages_unread': 'str',
        'messages_unprocessed': 'str'
    }

    attribute_map = {
        'to_id': 'to_id',
        'messages_unread': 'messages_unread',
        'messages_unprocessed': 'messages_unprocessed'
    }

    def __init__(self, to_id=None, messages_unread=None, messages_unprocessed=None):  # noqa: E501
        """MessagesCount - a model defined in Swagger"""  # noqa: E501
        self._to_id = None
        self._messages_unread = None
        self._messages_unprocessed = None
        self.discriminator = None
        if to_id is not None:
            self.to_id = to_id
        if messages_unread is not None:
            self.messages_unread = messages_unread
        if messages_unprocessed is not None:
            self.messages_unprocessed = messages_unprocessed

    @property
    def to_id(self):
        """Gets the to_id of this MessagesCount.  # noqa: E501


        :return: The to_id of this MessagesCount.  # noqa: E501
        :rtype: str
        """
        return self._to_id

    @to_id.setter
    def to_id(self, to_id):
        """Sets the to_id of this MessagesCount.


        :param to_id: The to_id of this MessagesCount.  # noqa: E501
        :type: str
        """

        self._to_id = to_id

    @property
    def messages_unread(self):
        """Gets the messages_unread of this MessagesCount.  # noqa: E501


        :return: The messages_unread of this MessagesCount.  # noqa: E501
        :rtype: str
        """
        return self._messages_unread

    @messages_unread.setter
    def messages_unread(self, messages_unread):
        """Sets the messages_unread of this MessagesCount.


        :param messages_unread: The messages_unread of this MessagesCount.  # noqa: E501
        :type: str
        """

        self._messages_unread = messages_unread

    @property
    def messages_unprocessed(self):
        """Gets the messages_unprocessed of this MessagesCount.  # noqa: E501


        :return: The messages_unprocessed of this MessagesCount.  # noqa: E501
        :rtype: str
        """
        return self._messages_unprocessed

    @messages_unprocessed.setter
    def messages_unprocessed(self, messages_unprocessed):
        """Sets the messages_unprocessed of this MessagesCount.


        :param messages_unprocessed: The messages_unprocessed of this MessagesCount.  # noqa: E501
        :type: str
        """

        self._messages_unprocessed = messages_unprocessed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessagesCount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagesCount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
