# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.177.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UsageReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_list': 'ProductList',
        'price_list': 'PriceList',
        'allowance_list': 'AllowanceList',
        'usage_list': 'list[Usage]'
    }

    attribute_map = {
        'product_list': 'product_list',
        'price_list': 'price_list',
        'allowance_list': 'allowance_list',
        'usage_list': 'usage_list'
    }

    def __init__(self, product_list=None, price_list=None, allowance_list=None, usage_list=None):  # noqa: E501
        """UsageReport - a model defined in Swagger"""  # noqa: E501
        self._product_list = None
        self._price_list = None
        self._allowance_list = None
        self._usage_list = None
        self.discriminator = None
        if product_list is not None:
            self.product_list = product_list
        if price_list is not None:
            self.price_list = price_list
        if allowance_list is not None:
            self.allowance_list = allowance_list
        if usage_list is not None:
            self.usage_list = usage_list

    @property
    def product_list(self):
        """Gets the product_list of this UsageReport.  # noqa: E501


        :return: The product_list of this UsageReport.  # noqa: E501
        :rtype: ProductList
        """
        return self._product_list

    @product_list.setter
    def product_list(self, product_list):
        """Sets the product_list of this UsageReport.


        :param product_list: The product_list of this UsageReport.  # noqa: E501
        :type: ProductList
        """

        self._product_list = product_list

    @property
    def price_list(self):
        """Gets the price_list of this UsageReport.  # noqa: E501


        :return: The price_list of this UsageReport.  # noqa: E501
        :rtype: PriceList
        """
        return self._price_list

    @price_list.setter
    def price_list(self, price_list):
        """Sets the price_list of this UsageReport.


        :param price_list: The price_list of this UsageReport.  # noqa: E501
        :type: PriceList
        """

        self._price_list = price_list

    @property
    def allowance_list(self):
        """Gets the allowance_list of this UsageReport.  # noqa: E501


        :return: The allowance_list of this UsageReport.  # noqa: E501
        :rtype: AllowanceList
        """
        return self._allowance_list

    @allowance_list.setter
    def allowance_list(self, allowance_list):
        """Sets the allowance_list of this UsageReport.


        :param allowance_list: The allowance_list of this UsageReport.  # noqa: E501
        :type: AllowanceList
        """

        self._allowance_list = allowance_list

    @property
    def usage_list(self):
        """Gets the usage_list of this UsageReport.  # noqa: E501


        :return: The usage_list of this UsageReport.  # noqa: E501
        :rtype: list[Usage]
        """
        return self._usage_list

    @usage_list.setter
    def usage_list(self, usage_list):
        """Sets the usage_list of this UsageReport.


        :param usage_list: The usage_list of this UsageReport.  # noqa: E501
        :type: list[Usage]
        """

        self._usage_list = usage_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsageReport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsageReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
