
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-10T05:54:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "644f09fa351bdc14ba945e372df94fd990b9c690",
 "version": "2023.11.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
