# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_types.proto\x12\x06gs.rpc\"\x1c\n\x0b\x44oubleValue\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1b\n\nFloatValue\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1b\n\nInt64Value\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1c\n\x0bUInt64Value\x12\r\n\x05value\x18\x01 \x01(\x04\"\x1b\n\nInt32Value\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\x0bUInt32Value\x12\r\n\x05value\x18\x01 \x01(\r\"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nBytesValue\x12\r\n\x05value\x18\x01 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOUBLEVALUE._serialized_start=28
  _DOUBLEVALUE._serialized_end=56
  _FLOATVALUE._serialized_start=58
  _FLOATVALUE._serialized_end=85
  _INT64VALUE._serialized_start=87
  _INT64VALUE._serialized_end=114
  _UINT64VALUE._serialized_start=116
  _UINT64VALUE._serialized_end=144
  _INT32VALUE._serialized_start=146
  _INT32VALUE._serialized_end=173
  _UINT32VALUE._serialized_start=175
  _UINT32VALUE._serialized_end=203
  _BOOLVALUE._serialized_start=205
  _BOOLVALUE._serialized_end=231
  _STRINGVALUE._serialized_start=233
  _STRINGVALUE._serialized_end=261
  _BYTESVALUE._serialized_start=263
  _BYTESVALUE._serialized_end=290
# @@protoc_insertion_point(module_scope)
