# Generated by Django 4.2.3 on 2023-11-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_model", "0011_remove_userdislikecategorylayerparameterlog_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermealtaglog",
            name="user_meal_tag",
        ),
        migrations.DeleteModel(
            name="UserDislikeCategoryLayerParameterLog",
        ),
        migrations.DeleteModel(
            name="UserMealTagLog",
        ),
    ]
