
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-11T07:10:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f802ab2ddb5f960218f88d1e984417cdbe94bc8",
 "version": "2.17.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
