import torch.nn as nn
from _typeshed import Incomplete
from typing import List

class SearchableOperationsContainer(nn.Module):
    base_search_block: Incomplete
    activation: Incomplete
    def __init__(self, operations: List[nn.Module], **extra_options) -> None: ...
    def forward(self, *args, **kwargs): ...
    def get_op_by_index(self, index: int) -> nn.Module: ...
    def share_affine_for_last_batchnorms(self, *search_block_args, **search_block_kwargs) -> None: ...
