
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-12T11:53:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2727b74f80b3eacf432bdd2fbc5063c9bda247a4",
 "version": "2.24.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
