# coding: utf-8

"""
    Cloudhub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TrustServiceAuthParametersModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_info': 'TrustServiceInfoModel',
        'auth_url': 'str'
    }

    attribute_map = {
        'service_info': 'serviceInfo',
        'auth_url': 'authUrl'
    }

    def __init__(self, service_info=None, auth_url=None):  # noqa: E501
        """TrustServiceAuthParametersModel - a model defined in Swagger"""  # noqa: E501
        self._service_info = None
        self._auth_url = None
        self.discriminator = None
        if service_info is not None:
            self.service_info = service_info
        if auth_url is not None:
            self.auth_url = auth_url

    @property
    def service_info(self):
        """Gets the service_info of this TrustServiceAuthParametersModel.  # noqa: E501


        :return: The service_info of this TrustServiceAuthParametersModel.  # noqa: E501
        :rtype: TrustServiceInfoModel
        """
        return self._service_info

    @service_info.setter
    def service_info(self, service_info):
        """Sets the service_info of this TrustServiceAuthParametersModel.


        :param service_info: The service_info of this TrustServiceAuthParametersModel.  # noqa: E501
        :type: TrustServiceInfoModel
        """

        self._service_info = service_info

    @property
    def auth_url(self):
        """Gets the auth_url of this TrustServiceAuthParametersModel.  # noqa: E501


        :return: The auth_url of this TrustServiceAuthParametersModel.  # noqa: E501
        :rtype: str
        """
        return self._auth_url

    @auth_url.setter
    def auth_url(self, auth_url):
        """Sets the auth_url of this TrustServiceAuthParametersModel.


        :param auth_url: The auth_url of this TrustServiceAuthParametersModel.  # noqa: E501
        :type: str
        """

        self._auth_url = auth_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrustServiceAuthParametersModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrustServiceAuthParametersModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
