# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/set_metadata/v3/set_metadata.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf


@dataclass(eq=False, repr=False)
class Config(betterproto.Message):
    metadata_namespace: str = betterproto.string_field(1)
    """The metadata namespace."""

    value: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(2)
    """
    The value to update the namespace with. See :ref:`the filter documentation
    <config_http_filters_set_metadata>` for more information on how this value
    is merged with potentially existing ones.
    """
