
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-10T15:33:34-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0122dad7ba4e37b955e9a23e15628b81be47994b",
 "version": "2023.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
