# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.177.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bmb_martlet_organization_client
from bmb_martlet_organization_client.api.organizations_api import OrganizationsApi  # noqa: E501
from bmb_martlet_organization_client.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_address(self):
        """Test case for create_address

        Create an address  # noqa: E501
        """
        pass

    def test_create_oauth2_client(self):
        """Test case for create_oauth2_client

        Create an OAuth2 client  # noqa: E501
        """
        pass

    def test_create_permission(self):
        """Test case for create_permission

        Grant a permission.  # noqa: E501
        """
        pass

    def test_create_private_key(self):
        """Test case for create_private_key

        Rotate private key - create and store new key with life of 90 days.   # noqa: E501
        """
        pass

    def test_create_proxy(self):
        """Test case for create_proxy

        [create] Create an organization proxy.  # noqa: E501
        """
        pass

    def test_define_message_content_type(self):
        """Test case for define_message_content_type

        Define a message content type for an organization  # noqa: E501
        """
        pass

    def test_delete_oauth2_client(self):
        """Test case for delete_oauth2_client

        Delete an individual Oauth2Client  # noqa: E501
        """
        pass

    def test_delete_payment_method_link_for_organization(self):
        """Test case for delete_payment_method_link_for_organization

        Delete payment method link  # noqa: E501
        """
        pass

    def test_delete_permission(self):
        """Test case for delete_permission

        Remove a permission  # noqa: E501
        """
        pass

    def test_delete_proxy(self):
        """Test case for delete_proxy

        [delete] Delete a proxy.  # noqa: E501
        """
        pass

    def test_get_billing_address_history(self):
        """Test case for get_billing_address_history

        Gets the billing address history  # noqa: E501
        """
        pass

    def test_get_current_billing_address(self):
        """Test case for get_current_billing_address

        Gets the current billing address  # noqa: E501
        """
        pass

    def test_get_message_content_type(self):
        """Test case for get_message_content_type

        """
        pass

    def test_get_oauth2_client(self):
        """Test case for get_oauth2_client

        Get and individual Oauth2Client including client_secret  # noqa: E501
        """
        pass

    def test_get_organization(self):
        """Test case for get_organization

        Get details of an individual organization  # noqa: E501
        """
        pass

    def test_get_organization_certificate(self):
        """Test case for get_organization_certificate

        \"Get the certificate for an organization or a user.\"   # noqa: E501
        """
        pass

    def test_get_payment_method_link_for_organization(self):
        """Test case for get_payment_method_link_for_organization

        Get payment method link  # noqa: E501
        """
        pass

    def test_get_proxy(self):
        """Test case for get_proxy

        [get_proxy] Get details of an individual proxy  # noqa: E501
        """
        pass

    def test_get_public_key(self):
        """Test case for get_public_key

        Get the public key for a resource  # noqa: E501
        """
        pass

    def test_get_usage_report(self):
        """Test case for get_usage_report

        Gets information to calculate current charges  # noqa: E501
        """
        pass

    def test_list_addresses(self):
        """Test case for list_addresses

        list address  # noqa: E501
        """
        pass

    def test_list_message_content_types(self):
        """Test case for list_message_content_types

        """
        pass

    def test_list_oauth2_clients(self):
        """Test case for list_oauth2_clients

        Get the oauth2_clients for an organization.  # noqa: E501
        """
        pass

    def test_list_permissions(self):
        """Test case for list_permissions

        Get the permissions for an organization.  # noqa: E501
        """
        pass

    def test_list_private_keys(self):
        """Test case for list_private_keys

        Get the private keys for a resource.  # noqa: E501
        """
        pass

    def test_list_proxies(self):
        """Test case for list_proxies

        [get_proxies ] Returns the proxies for this organization.  # noqa: E501
        """
        pass

    def test_set_billing_address(self):
        """Test case for set_billing_address

        Sets a new billing address  # noqa: E501
        """
        pass

    def test_set_icon(self):
        """Test case for set_icon

        Set an icon for the organization  # noqa: E501
        """
        pass

    def test_set_organization_certificate(self):
        """Test case for set_organization_certificate

        Upload a new X.509 identity certificate   # noqa: E501
        """
        pass

    def test_update_organization(self):
        """Test case for update_organization

        Update organization object.  # noqa: E501
        """
        pass

    def test_update_private_key(self):
        """Test case for update_private_key

        Update a private key.  set_rescinded ============= {   \"op\": \"replace\",   \"path\": \"/rescinded\",   \"value\": true }   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
