# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.177.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bmb_martlet_organization_client
from bmb_martlet_organization_client.models.access_list_entries_response import AccessListEntriesResponse  # noqa: E501
from bmb_martlet_organization_client.rest import ApiException


class TestAccessListEntriesResponse(unittest.TestCase):
    """AccessListEntriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessListEntriesResponse(self):
        """Test AccessListEntriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bmb_martlet_organization_client.models.access_list_entries_response.AccessListEntriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
