# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.177.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bmb_martlet_organization_client
from bmb_martlet_organization_client.api.addresses_api import AddressesApi  # noqa: E501
from bmb_martlet_organization_client.rest import ApiException


class TestAddressesApi(unittest.TestCase):
    """AddressesApi unit test stubs"""

    def setUp(self):
        self.api = AddressesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_access_list(self):
        """Test case for activate_access_list

        \"create an activation record for this list. Removes any other list's activation record.\"   # noqa: E501
        """
        pass

    def test_create_access_list(self):
        """Test case for create_access_list

        Add an access list  # noqa: E501
        """
        pass

    def test_create_access_list_entry(self):
        """Test case for create_access_list_entry

        Add an entry to an access list  # noqa: E501
        """
        pass

    def test_create_message_processed_receipt(self):
        """Test case for create_message_processed_receipt

        Submit notification that a message has been processed  # noqa: E501
        """
        pass

    def test_create_note(self):
        """Test case for create_note

        Add a note for a message connected with this address  # noqa: E501
        """
        pass

    def test_create_permission(self):
        """Test case for create_permission

        Grant a permission.  # noqa: E501
        """
        pass

    def test_create_private_key(self):
        """Test case for create_private_key

        Rotate private key - create and store new key with life of 90 days.   # noqa: E501
        """
        pass

    def test_deactivate_access_list(self):
        """Test case for deactivate_access_list

        Delete an activation  # noqa: E501
        """
        pass

    def test_delete_access_list(self):
        """Test case for delete_access_list

        Delete a list  # noqa: E501
        """
        pass

    def test_delete_access_list_entry(self):
        """Test case for delete_access_list_entry

        Delete an access list entry  # noqa: E501
        """
        pass

    def test_delete_message_type(self):
        """Test case for delete_message_type

        Delete a message type  # noqa: E501
        """
        pass

    def test_delete_permission(self):
        """Test case for delete_permission

        Remove a permission  # noqa: E501
        """
        pass

    def test_get_access_list(self):
        """Test case for get_access_list

        get single access list  # noqa: E501
        """
        pass

    def test_get_address(self):
        """Test case for get_address

        get an address  # noqa: E501
        """
        pass

    def test_get_inbound_delivery_advice(self):
        """Test case for get_inbound_delivery_advice

        get the delivery advice for an inbound message, if any  # noqa: E501
        """
        pass

    def test_get_inbound_message(self):
        """Test case for get_inbound_message

        Get the specified message if received by this address  # noqa: E501
        """
        pass

    def test_get_message(self):
        """Test case for get_message

        Get a single message  # noqa: E501
        """
        pass

    def test_get_outbound_delivery_advice(self):
        """Test case for get_outbound_delivery_advice

        get the delivery advice for an outbound message, if any  # noqa: E501
        """
        pass

    def test_get_outbound_message(self):
        """Test case for get_outbound_message

        get an outbound message  # noqa: E501
        """
        pass

    def test_get_public_key(self):
        """Test case for get_public_key

        Get the public key for a resource  # noqa: E501
        """
        pass

    def test_get_rejection_notice(self):
        """Test case for get_rejection_notice

        get a rejected-message record  # noqa: E501
        """
        pass

    def test_get_submission_receipt(self):
        """Test case for get_submission_receipt

        get a received-message record  # noqa: E501
        """
        pass

    def test_list_access_list_entries(self):
        """Test case for list_access_list_entries

        Get list entries  # noqa: E501
        """
        pass

    def test_list_access_lists(self):
        """Test case for list_access_lists

        get access lists for address  # noqa: E501
        """
        pass

    def test_list_inbound_delivery_advices(self):
        """Test case for list_inbound_delivery_advices

        The messages sent to this address available for insertion/delivery. Requires bmbix://power/address/view.   # noqa: E501
        """
        pass

    def test_list_message_processed_receipts(self):
        """Test case for list_message_processed_receipts

        get processed receipts  # noqa: E501
        """
        pass

    def test_list_message_types(self):
        """Test case for list_message_types

        Message types processable by this address  # noqa: E501
        """
        pass

    def test_list_notes(self):
        """Test case for list_notes

        Message notes for messages connected with this address  # noqa: E501
        """
        pass

    def test_list_outbound_delivery_advices(self):
        """Test case for list_outbound_delivery_advices

        Get a report of all message acceptances send from this address  # noqa: E501
        """
        pass

    def test_list_permissions(self):
        """Test case for list_permissions

        Get the permissions for an organization.  # noqa: E501
        """
        pass

    def test_list_private_keys(self):
        """Test case for list_private_keys

        Get the private keys for a resource.  # noqa: E501
        """
        pass

    def test_list_rejection_notices(self):
        """Test case for list_rejection_notices

        get rejected-message records  # noqa: E501
        """
        pass

    def test_list_submission_receipts(self):
        """Test case for list_submission_receipts

        get received-message records  # noqa: E501
        """
        pass

    def test_mark_read(self):
        """Test case for mark_read

        mark a message as read  # noqa: E501
        """
        pass

    def test_register_message_type(self):
        """Test case for register_message_type

        Register a message-type processable by this address  # noqa: E501
        """
        pass

    def test_submit_message(self):
        """Test case for submit_message

        Make a message submission  # noqa: E501
        """
        pass

    def test_update_address(self):
        """Test case for update_address

        Update is_closed or purpose status  # noqa: E501
        """
        pass

    def test_update_private_key(self):
        """Test case for update_private_key

        Update a private key.  set_rescinded ============= {   \"op\": \"replace\",   \"path\": \"/rescinded\",   \"value\": true }   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
