
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-02T11:55:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "34fea6d9c2ff4a58cda16e56a680cbf3461a9a00",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
