# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-4YLMqsqwoEAXklxzOlbJYALTxdNVohM
"""

from setuptools import setup, find_packages
import codecs
import os

VERSION = '0.0.4'
DESCRIPTION = 'Lateral Dimensionality Reduction'
LONG_DESCRIPTION = 'Reduce the number of features in a pandas DataFrame by a squeezing the numerical features to half as many complex valued features'

# Setting up
setup(
    name="LatDi",
    version=VERSION,
    author="SussyMongoosey (Jack Martin)",
    author_email="<johnelliotmartin@gmail.com>",
    description=DESCRIPTION,
    long_description_content_type="text/markdown",
    long_description=LONG_DESCRIPTION,
    packages=find_packages(),
    install_requires=['pandas', 'numpy'],
    keywords=['python', 'pandas', 'numpy', 'feature engineering', 'dimensionality reduction'],
    classifiers=[
        "Development Status :: 1 - Planning",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Operating System :: Unix",
        "Operating System :: MacOS :: MacOS X",
        "Operating System :: Microsoft :: Windows",
    ]
)
