
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-13T14:33:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f497e97f4c31f69c1dd2cffa1e19fd2605994388",
 "version": "0.6.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
