
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-13T04:23:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "48606c1273c5cfe1a55106e2600294a45fb7438e",
 "version": "1.19.1.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
