
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-08T17:04:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "78c20541331dfa0262c6a3fb7cf5c2ace1e782a7",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
