
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-09T16:46:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "101f76be4e8fbec01659a3cd619e68092c38bc32",
 "version": "1.19.0.post0.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
