# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/passable',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/passable',
                'lib_path': 'passable'},
  'syms': { 'passable.core': { 'passable.core.npass': ('core.html#npass', 'passable/core.py'),
                               'passable.core.rpass': ('core.html#rpass', 'passable/core.py'),
                               'passable.core.upass': ('core.html#upass', 'passable/core.py'),
                               'passable.core.xpass': ('core.html#xpass', 'passable/core.py')}}}
