# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xpass',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/xpass',
                'lib_path': 'xpass'},
  'syms': { 'xpass.core': { 'xpass.core.apass': ('core.html#apass', 'xpass/core.py'),
                            'xpass.core.ipass': ('core.html#ipass', 'xpass/core.py'),
                            'xpass.core.npass': ('core.html#npass', 'xpass/core.py'),
                            'xpass.core.rpass': ('core.html#rpass', 'xpass/core.py'),
                            'xpass.core.upass': ('core.html#upass', 'xpass/core.py'),
                            'xpass.core.xpass': ('core.html#xpass', 'xpass/core.py')}}}
