
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-10T15:57:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "227f8fa894f6313d60c1b4b3b0fb12e7900c7248",
 "version": "1.61.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
