# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from boids_api.boids.base_model import Model
from boids_api import util


class SessionState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PENDING = 'PENDING'
    PAUSED = 'PAUSED'
    RESET = 'RESET'
    RUNNING = 'RUNNING'
    STEP = 'STEP'
    TERMINATED = 'TERMINATED'
    ARCHIVED = 'ARCHIVED'

    def __init__(self):
        """SessionState - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SessionState':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SessionState of this SessionState.
        """
        return util.deserialize_model(dikt, cls)
