# Generated by Django 4.2.3 on 2023-11-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_model", "0010_remove_usermealtaglog_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdislikecategorylayerparameterlog",
            name="user",
        ),
        migrations.AlterField(
            model_name="userdislikecategorylayerparameterlog",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="app_model.dislikecategorylayerparameter",
            ),
        ),
    ]
