
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-09T07:23:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e16c88d3237fb5ca6734f2dfa6f5a36fa4804f81",
 "version": "0.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
