// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: xla/pjrt/distributed/protocol.proto

#include "xla/pjrt/distributed/protocol.pb.h"
#include "xla/pjrt/distributed/protocol.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace xla {


namespace grpc {

} // namespace grpc

} // namespace xla

