
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-10T15:31:09-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d858bace7dccd6687d1995494dc185455cb076f",
 "version": "6.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
