
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-13T23:05:18-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "d58c8a055c29111d0dcdb552bf601d4a9fe1995f",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
