# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0btrade.proto\"\xa2\x01\n\x07Request\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x04 \x01(\t\x12\x15\n\rstrategy_name\x18\x05 \x01(\t\x12\r\n\x05phase\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\x02\x12\x0e\n\x06volume\x18\x08 \x01(\x05\x12\x13\n\x0bupdate_time\x18\t \x01(\t\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trade_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_REQUEST']._serialized_start = 16
    _globals['_REQUEST']._serialized_end = 178
    _globals['_RESPONSE']._serialized_start = 180
    _globals['_RESPONSE']._serialized_end = 223
# @@protoc_insertion_point(module_scope)
