# coding: utf-8

"""
    OGC API - Processes

    Example API Definition for OGC API - Processes  # noqa: E501

    The version of the OpenAPI document: 0.1
    Contact: info@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class StatusCode(str, Enum):
    """
    StatusCode
    """

    """
    allowed enum values
    """
    ACCEPTED = 'accepted'
    RUNNING = 'running'
    SUCCESSFUL = 'successful'
    FAILED = 'failed'
    DISMISSED = 'dismissed'

    @classmethod
    def from_json(cls, json_str: str) -> StatusCode:
        """Create an instance of StatusCode from a JSON string"""
        return StatusCode(json.loads(json_str))


