# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_strs.ipynb.

# %% auto 0
__all__ = ['StrLike', 'Strs', 'StrSet', 'StrTmpl']

# %% ../nbs/03_strs.ipynb 6
from string import Template

# %% ../nbs/03_strs.ipynb 8
from typing import (
    TypeAlias, Literal, Union, List, Set,
    Iterable, Tuple, ForwardRef
)

# %% ../nbs/03_strs.ipynb 10
#| export


# %% ../nbs/03_strs.ipynb 12
#| export


# %% ../nbs/03_strs.ipynb 14
#| export


# %% ../nbs/03_strs.ipynb 16
StrLike: TypeAlias = Union[str, 'strfix', 'fuzstr', 'nymstr', 'synset', 'brvstr', 'strfix']
Strs:    TypeAlias = List[StrLike]
StrSet:  TypeAlias = Set[StrLike]
StrTmpl: TypeAlias = Union[str, Template]
