# Generated by Django 4.2.3 on 2023-11-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_model", "0009_dietplan_first_day_diet_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermealtaglog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="usermealtaglog",
            name="user",
        ),
        migrations.AddField(
            model_name="usermealtaglog",
            name="user_meal_tag",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="app_model.usermealtag",
            ),
        ),
    ]
