# Generated by Django 4.2.3 on 2023-11-13 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_model", "0012_remove_usermealtaglog_user_meal_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDislikeCategoryLayerParameterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.IntegerField(
                        choices=[(0, "미정"), (1, "설정"), (-1, "해제")], default=0
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_logs",
                        to="app_model.dislikecategorylayerparameter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dislike_category_layer_parameter_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_userdislikecategorylayerparamegerlog",
            },
        ),
    ]
