# coding: utf-8

"""
    Event Ingestion API

    Event Ingestion API client for DataKitchen’s DataOps Observability  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@datakitchen.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import events_ingestion_client
from events_ingestion_client.models.test_gen_test_outcome_integrations_schema34df828f995647db96ab04c283947a9a import TestGenTestOutcomeIntegrationsSchema34df828f995647db96ab04c283947a9a  # noqa: E501
from events_ingestion_client.rest import ApiException


class TestTestGenTestOutcomeIntegrationsSchema34df828f995647db96ab04c283947a9a(unittest.TestCase):
    """TestGenTestOutcomeIntegrationsSchema34df828f995647db96ab04c283947a9a unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestGenTestOutcomeIntegrationsSchema34df828f995647db96ab04c283947a9a(self):
        """Test TestGenTestOutcomeIntegrationsSchema34df828f995647db96ab04c283947a9a"""
        # FIXME: construct object with mandatory attributes with example values
        # model = events_ingestion_client.models.test_gen_test_outcome_integrations_schema34df828f995647db96ab04c283947a9a.TestGenTestOutcomeIntegrationsSchema34df828f995647db96ab04c283947a9a()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
