# coding: utf-8

"""
    Event Ingestion API

    Event Ingestion API client for DataKitchen’s DataOps Observability  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@datakitchen.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import events_ingestion_client
from events_ingestion_client.models.test_outcome_item_integrations_schema3992479693eb4480_b52689b1274a3b81 import TestOutcomeItemIntegrationsSchema3992479693eb4480B52689b1274a3b81  # noqa: E501
from events_ingestion_client.rest import ApiException


class TestTestOutcomeItemIntegrationsSchema3992479693eb4480B52689b1274a3b81(unittest.TestCase):
    """TestOutcomeItemIntegrationsSchema3992479693eb4480B52689b1274a3b81 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestOutcomeItemIntegrationsSchema3992479693eb4480B52689b1274a3b81(self):
        """Test TestOutcomeItemIntegrationsSchema3992479693eb4480B52689b1274a3b81"""
        # FIXME: construct object with mandatory attributes with example values
        # model = events_ingestion_client.models.test_outcome_item_integrations_schema3992479693eb4480_b52689b1274a3b81.TestOutcomeItemIntegrationsSchema3992479693eb4480B52689b1274a3b81()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
