# coding: utf-8

"""
    Event Ingestion API

    Event Ingestion API client for DataKitchen’s DataOps Observability  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@datakitchen.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import events_ingestion_client
from events_ingestion_client.models.test_outcome_item_integrations import TestOutcomeItemIntegrations  # noqa: E501
from events_ingestion_client.rest import ApiException


class TestTestOutcomeItemIntegrations(unittest.TestCase):
    """TestOutcomeItemIntegrations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestOutcomeItemIntegrations(self):
        """Test TestOutcomeItemIntegrations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = events_ingestion_client.models.test_outcome_item_integrations.TestOutcomeItemIntegrations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
