# coding: utf-8

"""
    Event Ingestion API

    Event Ingestion API client for DataKitchen’s DataOps Observability  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@datakitchen.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import events_ingestion_client
from events_ingestion_client.models.all_of_test_gen_test_outcome_integration_component_schema9d180af518664df6_b59d77aba9bd9675_integrations import AllOfTestGenTestOutcomeIntegrationComponentSchema9d180af518664df6B59d77aba9bd9675Integrations  # noqa: E501
from events_ingestion_client.rest import ApiException


class TestAllOfTestGenTestOutcomeIntegrationComponentSchema9d180af518664df6B59d77aba9bd9675Integrations(unittest.TestCase):
    """AllOfTestGenTestOutcomeIntegrationComponentSchema9d180af518664df6B59d77aba9bd9675Integrations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfTestGenTestOutcomeIntegrationComponentSchema9d180af518664df6B59d77aba9bd9675Integrations(self):
        """Test AllOfTestGenTestOutcomeIntegrationComponentSchema9d180af518664df6B59d77aba9bd9675Integrations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = events_ingestion_client.models.all_of_test_gen_test_outcome_integration_component_schema9d180af518664df6_b59d77aba9bd9675_integrations.AllOfTestGenTestOutcomeIntegrationComponentSchema9d180af518664df6B59d77aba9bd9675Integrations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
