# coding: utf-8

"""
    Event Ingestion API

    Event Ingestion API client for DataKitchen’s DataOps Observability  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@datakitchen.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import events_ingestion_client
from events_ingestion_client.models.testgen_table_schema_afa35dff7b3e41b5_a799064fd2904a68 import TestgenTableSchemaAfa35dff7b3e41b5A799064fd2904a68  # noqa: E501
from events_ingestion_client.rest import ApiException


class TestTestgenTableSchemaAfa35dff7b3e41b5A799064fd2904a68(unittest.TestCase):
    """TestgenTableSchemaAfa35dff7b3e41b5A799064fd2904a68 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestgenTableSchemaAfa35dff7b3e41b5A799064fd2904a68(self):
        """Test TestgenTableSchemaAfa35dff7b3e41b5A799064fd2904a68"""
        # FIXME: construct object with mandatory attributes with example values
        # model = events_ingestion_client.models.testgen_table_schema_afa35dff7b3e41b5_a799064fd2904a68.TestgenTableSchemaAfa35dff7b3e41b5A799064fd2904a68()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
