# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/adic',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/adic',
                'lib_path': 'adic'},
  'syms': { 'adic.core': { 'adic.core.adic': ('core.html#adic', 'adic/core.py'),
                           'adic.core.adic.__dir__': ('core.html#adic.__dir__', 'adic/core.py'),
                           'adic.core.adic.__init__': ('core.html#adic.__init__', 'adic/core.py'),
                           'adic.core.adic.__setattr__': ('core.html#adic.__setattr__', 'adic/core.py'),
                           'adic.core.adic.__setitem__': ('core.html#adic.__setitem__', 'adic/core.py')}}}
