from enot.latency.latency_estimator.time_event import TimeEvent as TimeEvent
from typing import List, Union

class ItemLatencyRecord:
    def __init__(self, n_samples: Union[float, int] = ...) -> None: ...
    def add_event(self, event: TimeEvent) -> None: ...
    def total_time(self) -> float: ...
    def total_samples(self) -> float: ...
    @property
    def time_events(self) -> List[TimeEvent]: ...
