pdf_names=['ksone', 'kstwobign', 'norm', 'alpha', 'beta', 'betaprime', 'burr', 'burr12', 'fisk', 
           'cauchy', 'chi', 'chi2', 'expon', 'exponnorm', 'exponweib', 'exponpow',  'foldcauchy', 'f', 
           'foldnorm', 'weibull_min', 'weibull_max', 'genlogistic', 'genpareto', 
           'genextreme', 'gamma', 'gengamma', 'gompertz', 'gumbel_r', 
           'gumbel_l', 'hypsecant', 'invgamma', 'invgauss', 'norminvgauss', 
           'invweibull', 'johnsonsb', 'johnsonsu', 'laplace', 'laplace_asymmetric', 'levy', 'levy_l', 
           'logistic', 'loggamma', 'loglaplace', 'lognorm', 'gibrat', 'gilbrat', 'maxwell', 'mielke', 
           'kappa4', 'moyal', 'nakagami', 'ncx2', 't', 'pareto', 'powerlaw', 'powerlognorm', 
           'powernorm', 'rayleigh', 'reciprocal', 'rice', 'recipinvgauss', 'skewnorm', 'trapz', 
           'truncexpon', 'truncpareto', 'wald', 'gennorm', 'crystalball', 'argus']

pdf_common=['norm', 'alpha', 'johnsonsb', 'johnsonsu', 'chi2', 'f', 'skewnorm',           
            'gamma', 'gumbel_r', 'gumbel_l', 'laplace','logistic', 'weibull_min',
            'lognorm', 'maxwell', 't', 'powerlaw']


from scipy import stats


def stats_fits():
    fname={}
    fname ["ksone"] = stats.ksone.fit
    fname ["kstwobign"] = stats.kstwobign.fit
    fname ["norm"] = stats.norm.fit
    fname ["alpha"] = stats.alpha.fit
    fname ["anglit"] = stats.anglit.fit
    fname ["arcsine"] = stats.arcsine.fit
    fname ["beta"] = stats.beta.fit
    fname ["betaprime"] = stats.betaprime.fit
    fname ["bradford"] = stats.bradford.fit
    fname ["burr"] = stats.burr.fit
    fname ["burr12"] = stats.burr12.fit
    fname ["fisk"] = stats.fisk.fit
    fname ["cauchy"] = stats.cauchy.fit
    fname ["chi"] = stats.chi.fit
    fname ["chi2"] = stats.chi2.fit
    fname ["cosine"] = stats.cosine.fit
    fname ["dgamma"] = stats.dgamma.fit
    fname ["dweibull"] = stats.dweibull.fit
    fname ["expon"] = stats.expon.fit
    fname ["exponnorm"] = stats.exponnorm.fit
    fname ["exponweib"] = stats.exponweib.fit
    fname ["exponpow"] = stats.exponpow.fit
    fname ["fatiguelife"] = stats.fatiguelife.fit
    fname ["foldcauchy"] = stats.foldcauchy.fit
    fname ["f"] = stats.f.fit
    fname ["foldnorm"] = stats.foldnorm.fit
    fname ["weibull_min"] = stats.weibull_min.fit
    fname ["weibull_max"] = stats.weibull_max.fit
    fname ["genlogistic"] = stats.genlogistic.fit
    fname ["genpareto"] = stats.genpareto.fit
    fname ["genexpon"] = stats.genexpon.fit
    fname ["genextreme"] = stats.genextreme.fit
    fname ["gamma"] = stats.gamma.fit
    fname ["erlang"] = stats.erlang.fit
    fname ["gengamma"] = stats.gengamma.fit
    fname ["genhalflogistic"] = stats.genhalflogistic.fit
    fname ["gompertz"] = stats.gompertz.fit
    fname ["gumbel_r"] = stats.gumbel_r.fit
    fname ["gumbel_l"] = stats.gumbel_l.fit
    fname ["halfcauchy"] = stats.halfcauchy.fit
    fname ["halflogistic"] = stats.halflogistic.fit
    fname ["halfnorm"] = stats.halfnorm.fit
    fname ["hypsecant"] = stats.hypsecant.fit
    fname ["invgamma"] = stats.invgamma.fit
    fname ["invgauss"] = stats.invgauss.fit
    fname ["norminvgauss"] = stats.norminvgauss.fit
    fname ["invweibull"] = stats.invweibull.fit
    fname ["johnsonsb"] = stats.johnsonsb.fit
    fname ["johnsonsu"] = stats.johnsonsu.fit
    fname ["laplace"] = stats.laplace.fit
    fname ["laplace_asymmetric"] = stats.laplace_asymmetric.fit
    fname ["levy"] = stats.levy.fit
    fname ["levy_l"] = stats.levy_l.fit
    fname ["logistic"] = stats.logistic.fit
    fname ["loggamma"] = stats.loggamma.fit
    fname ["loglaplace"] = stats.loglaplace.fit
    fname ["lognorm"] = stats.lognorm.fit
    fname ["gibrat"] = stats.gibrat.fit
    fname ["gilbrat"] = stats.gilbrat.fit
    fname ["maxwell"] = stats.maxwell.fit
    fname ["mielke"] = stats.mielke.fit
    fname ["kappa4"] = stats.kappa4.fit
    fname ["kappa3"] = stats.kappa3.fit
    fname ["moyal"] = stats.moyal.fit
    fname ["nakagami"] = stats.nakagami.fit
    fname ["ncx2"] = stats.ncx2.fit
    fname ["t"] = stats.t.fit
    fname ["nct"] = stats.nct.fit
    fname ["pareto"] = stats.pareto.fit
    fname ["lomax"] = stats.lomax.fit
    fname ["pearson3"] = stats.pearson3.fit
    fname ["powerlaw"] = stats.powerlaw.fit
    fname ["powerlognorm"] = stats.powerlognorm.fit
    fname ["powernorm"] = stats.powernorm.fit
    fname ["rdist"] = stats.rdist.fit
    fname ["rayleigh"] = stats.rayleigh.fit
    fname ["loguniform"] = stats.loguniform.fit
    fname ["reciprocal"] = stats.reciprocal.fit
    fname ["rice"] = stats.rice.fit
    fname ["recipinvgauss"] = stats.recipinvgauss.fit
    fname ["semicircular"] = stats.semicircular.fit
    fname ["skewcauchy"] = stats.skewcauchy.fit
    fname ["skewnorm"] = stats.skewnorm.fit
    fname ["trapezoid"] = stats.trapezoid.fit
    fname ["trapz"] = stats.trapz.fit
    fname ["triang"] = stats.triang.fit
    fname ["truncexpon"] = stats.truncexpon.fit
    fname ["truncnorm"] = stats.truncnorm.fit
    fname ["truncpareto"] = stats.truncpareto.fit
    fname ["tukeylambda"] = stats.tukeylambda.fit
    fname ["uniform"] = stats.uniform.fit
    fname ["vonmises"] = stats.vonmises.fit
    fname ["vonmises_line"] = stats.vonmises_line.fit
    fname ["wald"] = stats.wald.fit
    fname ["wrapcauchy"] = stats.wrapcauchy.fit
    fname ["gennorm"] = stats.gennorm.fit
    fname ["halfgennorm"] = stats.halfgennorm.fit
    fname ["crystalball"] = stats.crystalball.fit
    fname ["argus"] = stats.argus.fit
    return fname

###############################################
def stats_cdfs():    
    cname={}
    cname ["ksone"] = stats.ksone.cdf
    cname ["kstwobign"] = stats.kstwobign.cdf
    cname ["norm"] = stats.norm.cdf
    cname ["alpha"] = stats.alpha.cdf
    cname ["anglit"] = stats.anglit.cdf
    cname ["arcsine"] = stats.arcsine.cdf
    cname ["beta"] = stats.beta.cdf
    cname ["betaprime"] = stats.betaprime.cdf
    cname ["bradford"] = stats.bradford.cdf
    cname ["burr"] = stats.burr.cdf
    cname ["burr12"] = stats.burr12.cdf
    cname ["fisk"] = stats.fisk.cdf
    cname ["cauchy"] = stats.cauchy.cdf
    cname ["chi"] = stats.chi.cdf
    cname ["chi2"] = stats.chi2.cdf
    cname ["cosine"] = stats.cosine.cdf
    cname ["dgamma"] = stats.dgamma.cdf
    cname ["dweibull"] = stats.dweibull.cdf
    cname ["expon"] = stats.expon.cdf
    cname ["exponnorm"] = stats.exponnorm.cdf
    cname ["exponweib"] = stats.exponweib.cdf
    cname ["exponpow"] = stats.exponpow.cdf
    cname ["fatiguelife"] = stats.fatiguelife.cdf
    cname ["foldcauchy"] = stats.foldcauchy.cdf
    cname ["f"] = stats.f.cdf
    cname ["foldnorm"] = stats.foldnorm.cdf
    cname ["weibull_min"] = stats.weibull_min.cdf
    cname ["weibull_max"] = stats.weibull_max.cdf
    cname ["genlogistic"] = stats.genlogistic.cdf
    cname ["genpareto"] = stats.genpareto.cdf
    cname ["genexpon"] = stats.genexpon.cdf
    cname ["genextreme"] = stats.genextreme.cdf
    cname ["gamma"] = stats.gamma.cdf
    cname ["erlang"] = stats.erlang.cdf
    cname ["gengamma"] = stats.gengamma.cdf
    cname ["genhalflogistic"] = stats.genhalflogistic.cdf
    cname ["gompertz"] = stats.gompertz.cdf
    cname ["gumbel_r"] = stats.gumbel_r.cdf
    cname ["gumbel_l"] = stats.gumbel_l.cdf
    cname ["halfcauchy"] = stats.halfcauchy.cdf
    cname ["halflogistic"] = stats.halflogistic.cdf
    cname ["halfnorm"] = stats.halfnorm.cdf
    cname ["hypsecant"] = stats.hypsecant.cdf
    cname ["invgamma"] = stats.invgamma.cdf
    cname ["invgauss"] = stats.invgauss.cdf
    cname ["norminvgauss"] = stats.norminvgauss.cdf
    cname ["invweibull"] = stats.invweibull.cdf
    cname ["johnsonsb"] = stats.johnsonsb.cdf
    cname ["johnsonsu"] = stats.johnsonsu.cdf
    cname ["laplace"] = stats.laplace.cdf
    cname ["laplace_asymmetric"] = stats.laplace_asymmetric.cdf
    cname ["levy"] = stats.levy.cdf
    cname ["levy_l"] = stats.levy_l.cdf
    cname ["logistic"] = stats.logistic.cdf
    cname ["loggamma"] = stats.loggamma.cdf
    cname ["loglaplace"] = stats.loglaplace.cdf
    cname ["lognorm"] = stats.lognorm.cdf
    cname ["gibrat"] = stats.gibrat.cdf
    cname ["gilbrat"] = stats.gilbrat.cdf
    cname ["maxwell"] = stats.maxwell.cdf
    cname ["mielke"] = stats.mielke.cdf
    cname ["kappa4"] = stats.kappa4.cdf
    cname ["kappa3"] = stats.kappa3.cdf
    cname ["moyal"] = stats.moyal.cdf
    cname ["nakagami"] = stats.nakagami.cdf
    cname ["ncx2"] = stats.ncx2.cdf
    cname ["t"] = stats.t.cdf
    cname ["nct"] = stats.nct.cdf
    cname ["pareto"] = stats.pareto.cdf
    cname ["lomax"] = stats.lomax.cdf
    cname ["pearson3"] = stats.pearson3.cdf
    cname ["powerlaw"] = stats.powerlaw.cdf
    cname ["powerlognorm"] = stats.powerlognorm.cdf
    cname ["powernorm"] = stats.powernorm.cdf
    cname ["rdist"] = stats.rdist.cdf
    cname ["rayleigh"] = stats.rayleigh.cdf
    cname ["loguniform"] = stats.loguniform.cdf
    cname ["reciprocal"] = stats.reciprocal.cdf
    cname ["rice"] = stats.rice.cdf
    cname ["recipinvgauss"] = stats.recipinvgauss.cdf
    cname ["semicircular"] = stats.semicircular.cdf
    cname ["skewcauchy"] = stats.skewcauchy.cdf
    cname ["skewnorm"] = stats.skewnorm.cdf
    cname ["trapezoid"] = stats.trapezoid.cdf
    cname ["trapz"] = stats.trapz.cdf
    cname ["triang"] = stats.triang.cdf
    cname ["truncexpon"] = stats.truncexpon.cdf
    cname ["truncnorm"] = stats.truncnorm.cdf
    cname ["truncpareto"] = stats.truncpareto.cdf
    cname ["tukeylambda"] = stats.tukeylambda.cdf
    cname ["uniform"] = stats.uniform.cdf
    cname ["vonmises"] = stats.vonmises.cdf
    cname ["vonmises_line"] = stats.vonmises_line.cdf
    cname ["wald"] = stats.wald.cdf
    cname ["wrapcauchy"] = stats.wrapcauchy.cdf
    cname ["gennorm"] = stats.gennorm.cdf
    cname ["halfgennorm"] = stats.halfgennorm.cdf
    cname ["crystalball"] = stats.crystalball.cdf
    cname ["argus"] = stats.argus.cdf
    return cname
    
###############################################
def stats_pdfs():    
    pname={}
    pname ["ksone"] = stats.ksone.pdf
    pname ["kstwobign"] = stats.kstwobign.pdf
    pname ["norm"] = stats.norm.pdf
    pname ["alpha"] = stats.alpha.pdf
    pname ["anglit"] = stats.anglit.pdf
    pname ["arcsine"] = stats.arcsine.pdf
    pname ["beta"] = stats.beta.pdf
    pname ["betaprime"] = stats.betaprime.pdf
    pname ["bradford"] = stats.bradford.pdf
    pname ["burr"] = stats.burr.pdf
    pname ["burr12"] = stats.burr12.pdf
    pname ["fisk"] = stats.fisk.pdf
    pname ["cauchy"] = stats.cauchy.pdf
    pname ["chi"] = stats.chi.pdf
    pname ["chi2"] = stats.chi2.pdf
    pname ["cosine"] = stats.cosine.pdf
    pname ["dgamma"] = stats.dgamma.pdf
    pname ["dweibull"] = stats.dweibull.pdf
    pname ["expon"] = stats.expon.pdf
    pname ["exponnorm"] = stats.exponnorm.pdf
    pname ["exponweib"] = stats.exponweib.pdf
    pname ["exponpow"] = stats.exponpow.pdf
    pname ["fatiguelife"] = stats.fatiguelife.pdf
    pname ["foldcauchy"] = stats.foldcauchy.pdf
    pname ["f"] = stats.f.pdf
    pname ["foldnorm"] = stats.foldnorm.pdf
    pname ["weibull_min"] = stats.weibull_min.pdf
    pname ["weibull_max"] = stats.weibull_max.pdf
    pname ["genlogistic"] = stats.genlogistic.pdf
    pname ["genpareto"] = stats.genpareto.pdf
    pname ["genexpon"] = stats.genexpon.pdf
    pname ["genextreme"] = stats.genextreme.pdf
    pname ["gamma"] = stats.gamma.pdf
    pname ["erlang"] = stats.erlang.pdf
    pname ["gengamma"] = stats.gengamma.pdf
    pname ["genhalflogistic"] = stats.genhalflogistic.pdf
    pname ["gompertz"] = stats.gompertz.pdf
    pname ["gumbel_r"] = stats.gumbel_r.pdf
    pname ["gumbel_l"] = stats.gumbel_l.pdf
    pname ["halfcauchy"] = stats.halfcauchy.pdf
    pname ["halflogistic"] = stats.halflogistic.pdf
    pname ["halfnorm"] = stats.halfnorm.pdf
    pname ["hypsecant"] = stats.hypsecant.pdf
    pname ["invgamma"] = stats.invgamma.pdf
    pname ["invgauss"] = stats.invgauss.pdf
    pname ["norminvgauss"] = stats.norminvgauss.pdf
    pname ["invweibull"] = stats.invweibull.pdf
    pname ["johnsonsb"] = stats.johnsonsb.pdf
    pname ["johnsonsu"] = stats.johnsonsu.pdf
    pname ["laplace"] = stats.laplace.pdf
    pname ["laplace_asymmetric"] = stats.laplace_asymmetric.pdf
    pname ["levy"] = stats.levy.pdf
    pname ["levy_l"] = stats.levy_l.pdf
    pname ["logistic"] = stats.logistic.pdf
    pname ["loggamma"] = stats.loggamma.pdf
    pname ["loglaplace"] = stats.loglaplace.pdf
    pname ["lognorm"] = stats.lognorm.pdf
    pname ["gibrat"] = stats.gibrat.pdf
    pname ["gilbrat"] = stats.gilbrat.pdf
    pname ["maxwell"] = stats.maxwell.pdf
    pname ["mielke"] = stats.mielke.pdf
    pname ["kappa4"] = stats.kappa4.pdf
    pname ["kappa3"] = stats.kappa3.pdf
    pname ["moyal"] = stats.moyal.pdf
    pname ["nakagami"] = stats.nakagami.pdf
    pname ["ncx2"] = stats.ncx2.pdf
    pname ["t"] = stats.t.pdf
    pname ["nct"] = stats.nct.pdf
    pname ["pareto"] = stats.pareto.pdf
    pname ["lomax"] = stats.lomax.pdf
    pname ["pearson3"] = stats.pearson3.pdf
    pname ["powerlaw"] = stats.powerlaw.pdf
    pname ["powerlognorm"] = stats.powerlognorm.pdf
    pname ["powernorm"] = stats.powernorm.pdf
    pname ["rdist"] = stats.rdist.pdf
    pname ["rayleigh"] = stats.rayleigh.pdf
    pname ["loguniform"] = stats.loguniform.pdf
    pname ["reciprocal"] = stats.reciprocal.pdf
    pname ["rice"] = stats.rice.pdf
    pname ["recipinvgauss"] = stats.recipinvgauss.pdf
    pname ["semicircular"] = stats.semicircular.pdf
    pname ["skewcauchy"] = stats.skewcauchy.pdf
    pname ["skewnorm"] = stats.skewnorm.pdf
    pname ["trapezoid"] = stats.trapezoid.pdf
    pname ["trapz"] = stats.trapz.pdf
    pname ["triang"] = stats.triang.pdf
    pname ["truncexpon"] = stats.truncexpon.pdf
    pname ["truncnorm"] = stats.truncnorm.pdf
    pname ["truncpareto"] = stats.truncpareto.pdf
    pname ["tukeylambda"] = stats.tukeylambda.pdf
    pname ["uniform"] = stats.uniform.pdf
    pname ["vonmises"] = stats.vonmises.pdf
    pname ["vonmises_line"] = stats.vonmises_line.pdf
    pname ["wald"] = stats.wald.pdf
    pname ["wrapcauchy"] = stats.wrapcauchy.pdf
    pname ["gennorm"] = stats.gennorm.pdf
    pname ["halfgennorm"] = stats.halfgennorm.pdf
    pname ["crystalball"] = stats.crystalball.pdf
    pname ["argus"] = stats.argus.pdf
    return pname    
    
def stats_npa():    
    npa={}
    npa["ksone"] = 3
    npa["kstwobign"] = 2
    npa["norm"] = 2
    npa["alpha"] = 3
    npa["beta"] = 4
    npa["betaprime"] = 4
    npa["burr"] = 4
    npa["burr12"] = 4
    npa["fisk"] = 3
    npa["cauchy"] = 2
    npa["chi"] = 3
    npa["chi2"] = 3
    npa["expon"] = 2
    npa["exponnorm"] = 3
    npa["exponweib"] = 4
    npa["exponpow"] = 3
    npa["foldcauchy"] = 3
    npa["f"] = 4
    npa["foldnorm"] = 3
    npa["weibull_min"] = 3
    npa["weibull_max"] = 3
    npa["genlogistic"] = 3
    npa["genpareto"] = 3
    npa["genextreme"] = 3
    npa["gamma"] = 3
    npa["gengamma"] = 4
    npa["gompertz"] = 3
    npa["gumbel_r"] = 2
    npa["gumbel_l"] = 2
    npa["hypsecant"] = 2
    npa["invgamma"] = 3
    npa["invgauss"] = 3
    npa["norminvgauss"] = 4
    npa["invweibull"] = 3
    npa["johnsonsb"] = 4
    npa["johnsonsu"] = 4
    npa["laplace"] = 2
    npa["laplace_asymmetric"] = 3
    npa["levy"] = 2
    npa["levy_l"] = 2
    npa["logistic"] = 2
    npa["loggamma"] = 3
    npa["loglaplace"] = 3
    npa["lognorm"] = 3
    npa["gibrat"] = 2
    npa["gilbrat"] = 2
    npa["maxwell"] = 2
    npa["mielke"] = 4
    npa["kappa4"] = 4
    npa["moyal"] = 2
    npa["nakagami"] = 3
    npa["ncx2"] = 4
    npa["t"] = 3
    npa["pareto"] = 3
    npa["powerlaw"] = 3
    npa["powerlognorm"] = 4
    npa["powernorm"] = 3
    npa["rayleigh"] = 2
    npa["reciprocal"] = 4
    npa["rice"] = 3
    npa["recipinvgauss"] = 3
    npa["skewnorm"] = 3
    npa["trapz"] = 4
    npa["truncexpon"] = 3
    npa["truncpareto"] = 4
    npa["wald"] = 2
    npa["gennorm"] = 3
    npa["crystalball"] = 4
    npa["argus"] = 3
    return npa
