
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-10T05:59:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1cf185c4d06adec4149004f1993933d768a2beac",
 "version": "2023.11.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
