print("..-. ...- -... / .... -.-- .-.. / .. .-.. .--. ..- -. / -.. .... .- .--- --- .-.. -.- .-.-.- .-.-.- .-.-.- / .--. / .- --- .--. ..- .-. / .- --- .-.. ..-. / .... -.-- .-.. / ...- ..- .- ...- / ..-. ...- -... .-.-.- .-.-.- .-.-.- / .--. / --- .... -.-. .-.. / --.. .-.. ..- .- / ..-. ...- -... / -.. --- .... .- / ..-. ...- -... / ..- .-.. .-.. -.- .-.-.- .-.-.- .-.-.- / -.. --- .-.. ..- / ..-. ...- -... / .... -.-- .-.. / -.-- .-.. .... -.- ..-. --..-- / -. .-.. .- / .- --- .-.. / -.- .... .- .... .-.-.- .-.-.- .-.-.- / / -.. .-.. / -.. .--. ... ... / -- ...- .--- -... --.. / ...- ..- / .- --- .-.. / .--- .... .-- .--. .- .... ... .-.-.- .-.-.- .-.-.- / ...- ..- .--- .-.. / ..-. ...- -... / --- .... -.-. .-.. / .... / .--- ... .-.. .... -.-- / ... .--. ..- .-.. / ...- -- / --.. .--. -. --- .- --..-- / .- .... .-. .-.. / .... .--- .- .--. ...- ..- .-.-.- .-.-.- .-.-.-")

from .buy_packs import buy_packs
from .check_your_balance import check_your_balance
from .open_packs import open_packs
from .take_action import take_action
from .login import login
from .run import run
from .walk import walk
from .jump import jump
from .swim import swim
from .dance import dance
from .sing import sing
from .read import read
from .write import write
from .draw import draw
from .paint import paint
from .cook import cook
from .eat import eat
from .sleep import sleep
from .wakeup import wakeup
from .study import study
from .work import work
from .play import play
from .laugh import laugh
from .cry import cry
from .hug import hug
from .kiss import kiss
from .drive import drive
from .fly import fly
from .travel import travel
from .shop import shop
from .exercise import exercise
from .meditate import meditate
from .pray import pray
from .build_it import build_it
from .create import create
from .solve import solve
from .solve import solve
from .plant import plant
from .water import water
from .clean import clean
from .organize import organize
from .teach import teach
from .learn import learn
from .code import code
from .design import design
from .sing import sing
from .ski import ski
from .skate import skate
from .ride import ride
from .bake import bake
from .sculpt import sculpt
from .film import film
from .edit import edit
from .publish import publish
from .volunteer import volunteer
from .get_the_data import get_the_data
from .help import help
from .listen import listen
from .give import give
from .receive import receive
from .compete import compete
from .collaborate import collaborate
from .communicate import communicate
from .negotiate import negotiate
from .plan import plan
from .manage import manage
from .lead import lead
from .follow import follow
from .support import support
from .mentor import mentor
from .innovate import innovate
from .explore import explore
from .adventure import adventure
from .camp import camp
from .fish import fish
from .hunt import hunt
from .climb import climb
from .race import race
from .solve import solve
from .invent import invent
from .document import document
from .discuss import discuss
from .share import share
from .program import program
from .test import test
from .debug import debug
from .analyze import analyze
from .improve import improve
from .invest import invest
from .save import save
from .budget import budget
from .dream import dream
from .imagine import imagine
from .achieve import achieve
from .celebrate import celebrate
from .relax import relax
from .party import party
from .chat import chat
from .socialize import socialize
from .network import network
from .compete import compete
from .win import win
from .new_data import new_data
from .lose import lose
from .debate import debate
from .watch import watch
from .listen import listen

#count_new_email = 0